---
title: "HTML Widgets Showcase"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    source: embed
---

Inputs {.sidebar}
-------------------------------------

### Example project

Some text about the project.

[Here is an example of a flexdashboard showcasing different kinds of visualizations in a "storyboard layout".](
https://beta.rstudioconnect.com/jjallaire/htmlwidgets-showcase-storyboard/htmlwidgets-showcase-storyboard.html)

Row
-------------------------------------
### Data Table - This is the first row first column of a grid layout
```{r}
library(ggplot2)
library(plotly)
p <- ggplot(data = diamonds, aes(x = cut, fill = clarity)) +
             geom_bar(position = position_dodge2(preserve = "total"))
ggplotly(p)
```

Row 
-------------------------------------
### This the second row first column of a grid layout
```{r}
library(pier)
data <- data.frame(label = c('Female','Male'),
                   value = c(1,3,0,0),
                   color = RColorBrewer::brewer.pal(4, 'Spectral'))

pier(data)
```

### Publication Type

```{r}
library(pier)
data <- data.frame(label = c('Journal Article','Chapter','Magazine Article', 'Dissertation/Thesis', 'Others'),
                   value = c(3,0,0,0,1),
                   color = RColorBrewer::brewer.pal(5, 'Spectral'))

pier(data)
```

Row
-------------------------------------
### This the third row first column of a grid layout
```{r}
library(DT)
datatable(iris, options = list(pageLength = 5))
```